version: "2"
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    ports:
      - "8080:80"
    links:
      - ekko-host

  ekko-host:
    build:
      context: ./
      dockerfile: docker/ekko-host.docker
    links:
      - database

  database:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=dev"
